dist: trusty
language: java
jdk:
        - oraclejdk8
addons:
  firefox: "75.0"
before_install:
        - sudo apt-get update
        - sudo apt-get install dbus-x11
        - export DISPLAY=:99.0
        - sh -e /etc/init.d/xvfb start
        - sudo apt-get install -y libappindicator1 fonts-liberation
        - wget https://github.com/mozilla/geckodriver/releases/download/v0.20.1/geckodriver-v0.20.1-linux64.tar.gz
        - tar -xzf geckodriver-v0.20.1-linux64.tar.gz
        - sudo cp geckodriver /usr/bin
